package dotty.tools.pc.buildinfo

// Real presentation-compiler build has this generated by sbt-buildinfo
// (`Compile / buildInfoPackage := "dotty.tools.pc.buildinfo"`,
// `Compile / buildInfoKeys := Seq(scalaVersion)` in `project/Build.scala`).
// Hand-written equivalent for scalino's own build, which has no sbt/
// buildinfo plugin in this pipeline.
object BuildInfo {
  val scalaVersion: String = dotty.tools.dotc.config.Properties.versionNumberString
}
