# Homebrew formula for a custom tap (e.g. lolgab/homebrew-scalino), not
# homebrew-core -- core requires building from source, and scalino's own
# build (build/all.sh) needs vendored/patched scala3+scala-native checkouts
# that don't fit homebrew-core's "build from source in a sandbox" model.
# This formula just installs the prebuilt, already-relocatable release
# tarball, same one install.sh fetches.
#
# url/sha256 below are regenerated by build/10-update-package-metadata.sh
# after every tagged release -- don't hand-edit them.
class Scalino < Formula
  desc "Scala 3 toolchain that compiles straight to native binaries -- no JVM at any step"
  homepage "https://github.com/lolgab/scalino"
  version "0.0.9"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-macos-x86_64.tar.gz"
      sha256 "62283afb32cd4f7dcecf84547687a618ada100cb94643957a71152d688241a87"
    end
    on_arm do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-macos-arm64.tar.gz"
      sha256 "054f6e3e066e23a9d118be53e5938b02a7edaaa5cde0a7d1d8bdfbb8287e48b3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-linux-x86_64.tar.gz"
      sha256 "a184e9242c16ef91c5e02e64233b417cd8c763f17aa79c86c490ec62e3d3af45"
    end
    on_arm do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-linux-arm64.tar.gz"
      sha256 "81a10fa1aa55deb519f3a599ef123390c63730b69564cc0b74e985099d922cd9"
    end
  end

  depends_on "llvm" => :recommended # provides clang/clang++ where the OS doesn't already (Linux); macOS uses Xcode CLT's own
  # coursier's `cs` launcher (needed for `//> using dep`) is bundled in the
  # tarball as scalino-cs -- no separate dependency.

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"scalino"
    bin.install_symlink libexec/"scalino-lsp"
    bin.install_symlink libexec/"scalino-cs"
  end

  test do
    system "#{bin}/scalino", "--help"
  end
end
