# Homebrew formula for a custom tap (e.g. lolgab/homebrew-scalino), not
# homebrew-core -- core requires building from source, and scalino's own
# build (build/all.sh) needs vendored/patched scala3+scala-native checkouts
# that don't fit homebrew-core's "build from source in a sandbox" model.
# This formula just installs the prebuilt, already-relocatable release
# tarball, same one install.sh fetches.
#
# url/sha256 below are regenerated by build/10-update-package-metadata.sh
# after every tagged release -- don't hand-edit them.
class Scalino < Formula
  desc "Scala 3 toolchain that compiles straight to native binaries -- no JVM at any step"
  homepage "https://github.com/lolgab/scalino"
  version "0.0.8"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-macos-x86_64.tar.gz"
      sha256 "1dc1e5c35ca3202e29ec259da215394c3127eeb0fed999c6c610fe453112747d"
    end
    on_arm do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-macos-arm64.tar.gz"
      sha256 "ae21781154703b1dcae62fa1d10e5950565528685b20588311d07729995d2d7d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-linux-x86_64.tar.gz"
      sha256 "249b65aa3b9773253f75586eb6c111f8f33caaa284b3827dda39a952fbe34da5"
    end
    on_arm do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-linux-arm64.tar.gz"
      sha256 "6b61d9cf0563bb3378afee2e651b66bd38bec730c1dafbfbd4427ecf34c088b0"
    end
  end

  depends_on "llvm" => :recommended # provides clang/clang++ where the OS doesn't already (Linux); macOS uses Xcode CLT's own
  # coursier's `cs` launcher (needed for `//> using dep`) is bundled in the
  # tarball as scalino-cs -- no separate dependency.

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"scalino"
    bin.install_symlink libexec/"scalino-lsp"
    bin.install_symlink libexec/"scalino-cs"
  end

  test do
    system "#{bin}/scalino", "--help"
  end
end
